# Generated by Django 4.1.7 on 2023-03-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=60)),
                ('recipe_type', models.CharField(choices=[('M', 'Meat'), ('Ve', 'Vegan'), ('V', 'Vegetarian')], max_length=12)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoration.chef')),
            ],
            options={
                'ordering': ['recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=60)),
                ('recipes', models.ManyToManyField(to='restoration.recipe')),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
    ]
