# Generated by Django 4.1.7 on 2023-03-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='headmaster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restoration.ceo'),
            preserve_default=False,
        ),
    ]
